version: '3'
services:
  node1:
    image: aeternity/aeternity:v5.5.4
    hostname: node1
    environment:
      AETERNITY_CONFIG: /home/aeternity/aeternity.yaml
    volumes:
      - ./docker/aeternity_node1_mean15.yaml:/home/aeternity/aeternity.yaml

  proxy:
    image: 'library/nginx:1.17.9'
    hostname: proxy
    ports:
      - '3001:3001'
    volumes:
      - './docker/nginx-default.conf:/etc/nginx/conf.d/default.conf'

volumes:
  node1_db:
