http:
  external:
    port: 3013
  internal:
    debug_endpoints: true
    port: 3113
    listen_address: 0.0.0.0

websocket:
  channel:
    listen_address: 0.0.0.0
    port: 3014

chain:
  persist: true
  hard_forks:
    "1": 0
    "2": 1
    "3": 2
    "4": 3

logging:
  level: info

mining:
  autostart: true
  beneficiary: "ak_2mwRmUeYmfuW93ti9HMSUJzCk1EYcQEfikVSzgo6k2VghsWhgU"
  beneficiary_reward_delay: 2
  expected_mine_rate: 4000
  micro_block_cycle: 1000
  cuckoo:
    edge_bits: 15
    miners:
      - executable: mean15-generic
        extra_args: "-t 1"

fork_management:
  network_id: "ae_devnet"
